Abbreviation.create :acronym => 'approx', :meaning => 'approximately'
Abbreviation.create :acronym => 'beg', :meaning => 'beginning'
Abbreviation.create :acronym => 'cc', :meaning => 'contrasting color'
Abbreviation.create :acronym => 'ch', :meaning => 'chain'
Abbreviation.create :acronym => 'cn', :meaning => 'cable needle'
Abbreviation.create :acronym => 'cont', :meaning => 'continue'
Abbreviation.create :acronym => 'dec', :meaning => 'decrease(s)'
Abbreviation.create :acronym => 'dpn', :meaning => 'double-pointed needles'
Abbreviation.create :acronym => 'foll', :meaning => 'follow'
Abbreviation.create :acronym => 'inc', :meaning => 'increase(s)'
Abbreviation.create :acronym => 'k', :meaning => 'knit'
Abbreviation.create :acronym => 'k2tog', :meaning => 'knit two stitches together'
Abbreviation.create :acronym => 'k-b', :meaning => 'knit through the back loop'
Abbreviation.create :acronym => 'k-wise', :meaning => 'knitwise'
Abbreviation.create :acronym => 'lp', :meaning => 'loop(s)'
Abbreviation.create :acronym => 'mc', :meaning => 'main color'
Abbreviation.create :acronym => 'm1', :meaning => 'make one stitch'
Abbreviation.create :acronym => 'p', :meaning => 'purl'
Abbreviation.create :acronym => 'p-b', :meaning => 'purl through the back loop'
Abbreviation.create :acronym => 'pm', :meaning => 'place marker'
Abbreviation.create :acronym => 'psso', :meaning => 'pass slipped stich over'
Abbreviation.create :acronym => 'pwise', :meaning => 'purlwise'
Abbreviation.create :acronym => 'rem', :meaning => 'remaining'
Abbreviation.create :acronym => 'rep', :meaning => 'repeat'
Abbreviation.create :acronym => 'rs', :meaning => 'right side'
Abbreviation.create :acronym => 'k-b', :meaning => 'knit through the back loop'
Abbreviation.create :acronym => 'rnd', :meaning => 'round(s)'
Abbreviation.create :acronym => 'sc', :meaning => 'single crochet'
Abbreviation.create :acronym => 'sl', :meaning => 'slip'
Abbreviation.create :acronym => 'sl st', :meaning => 'slip stitch'
Abbreviation.create :acronym => 'ssk', :meaning => 'slip, slip, knit the slipped stitches together'
Abbreviation.create :acronym => 'st', :meaning => 'stitches'
Abbreviation.create :acronym => 'tbl', :meaning => 'knit through the back loop'
Abbreviation.create :acronym => 'tog', :meaning => 'together'
Abbreviation.create :acronym => 'ws', :meaning => 'wrong side'
Abbreviation.create :acronym => 'wyib', :meaning => 'with yarn in the back'
Abbreviation.create :acronym => 'wyif', :meaning => 'with yarn in the front'
Abbreviation.create :acronym => 'yb', :meaning => 'yarn back'
Abbreviation.create :acronym => 'yf', :meaning => 'yarn forward'
Abbreviation.create :acronym => 'yo', :meaning => 'yarn over'
Abbreviation.create :acronym => 'yrn', :meaning => 'yarn around needle'


 